'''
"posts": [
        {
            "company": "Karat",
            "content": "神奇的店面，不好分类，希望能被人看到。。。\n烙印，经典亚马逊客服低质麦克风。已经和烙印工作多年的我仍然只听得懂50%。但好在对方也察觉到了，于是我委婉的希望对方讲慢一点，改善了很多。\n上来说了不要求你做完所有题目。只有一个code pad，我用java做的，纯靠main跑。\n第一题，输入是一个密码，需要判断密码是否合规，列出违反的规则。\n长度大于15\n不能包含“密码”，不区分大小写\n必须有一个大写一个小写\n必须包含三个特殊符号中的一个\n同一字符不能超过四个\n第二题：三个table，均以2D string array形式出现。然后进行match和join。\n有顾客表：名字，邮箱，商品名，购买数量 （一个用户只买一种商品）\n订单表：用户id，邮箱，订单总金额 （邮箱可以是null）\n商品表：商品名，单价。\n需要找出用户id到名字的mapping。\n面试官除了给题目以外一点用没有。\n求米🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏",
            "content_enhanced": "## Problem\nYou are given three tables represented as **2D string arrays** (each row is a record, no headers). You need to produce a mapping from **`userId` → `customerName`** by matching and joining information across tables.\n\n### Table 1: `customers`\nEach row: `[customerName, email, productName, quantity]`\n- `quantity` is an integer in string form.\n- Assumption: **each customer buys only one type of product** (i.e., one `productName` per customer).\n\n### Table 2: `orders`\nEach row: `[userId, email, orderTotal]`\n- `orderTotal` is a number in string form (integer or decimal).\n- `email` **may be null** (or an empty string, depending on how the input is represented).\n\n### Table 3: `products`\nEach row: `[productName, unitPrice]`\n- `unitPrice` is a number in string form.\n\n## Matching / Join requirement\nFor each `order` record, identify which customer placed it, then output `userId -> customerName`.\n\nUse these matching rules:\n1. If `orders.email` is present (non-null/non-empty), match the customer by **email**.\n2. If `orders.email` is missing, match by using the fact that:\n   - `orderTotal = quantity * unitPrice` for the customer’s purchased product.\n   - Use `customers.productName` joined to `products.productName` to get `unitPrice`.\n\n## Output\nReturn a mapping/dictionary from `userId` to `customerName` for all orders.\n\n## Assumptions / Edge cases\n- If multiple customers could match an order (e.g., same computed total), specify and implement a deterministic tie-breaker (e.g., pick lexicographically smallest name) or return all candidates—clarify with the interviewer.\n- Assume inputs are well-formed aside from possible null/empty emails.\n",
            "content_raw": "## Problem\nYou are given three tables represented as **2D string arrays** (each row is a record, no headers). You need to produce a mapping from **`userId` → `customerName`** by matching and joining information across tables.\n\n### Table 1: `customers`\nEach row: `[customerName, email, productName, quantity]`\n- `quantity` is an integer in string form.\n- Assumption: **each customer buys only one type of product** (i.e., one `productName` per customer).\n\n### Table 2: `orders`\nEach row: `[userId, email, orderTotal]`\n- `orderTotal` is a number in string form (integer or decimal).\n- `email` **may be null** (or an empty string, depending on how the input is represented).\n\n### Table 3: `products`\nEach row: `[productName, unitPrice]`\n- `unitPrice` is a number in string form.\n\n## Matching / Join requirement\nFor each `order` record, identify which customer placed it, then output `userId -> customerName`.\n\nUse these matching rules:\n1. If `orders.email` is present (non-null/non-empty), match the customer by **email**.\n2. If `orders.email` is missing, match by using the fact that:\n   - `orderTotal = quantity * unitPrice` for the customer’s purchased product.\n   - Use `customers.productName` joined to `products.productName` to get `unitPrice`.\n\n## Output\nReturn a mapping/dictionary from `userId` to `customerName` for all orders.\n\n## Assumptions / Edge cases\n- If multiple customers could match an order (e.g., same computed total), specify and implement a deterministic tie-breaker (e.g., pick lexicographically smallest name) or return all candidates—clarify with the interviewer.\n- Assume inputs are well-formed aside from possible null/empty emails.\n",
            "created_at": "2026-01-22T00:00:00",
            "difficulty": "medium",
            "has_coding_schema": false,
            "has_schema_data": false,
            "id": 6017,
            "interview_round": "Technical Screen",
            "is_liked": false,
            "is_locked": false,
            "is_saved": false,
            "is_shared": false,
            "likes": [],
            "likes_count": 0,
            "position": "Software Engineer",
            "real_comments_count": 0,
            "real_likes_count": 0,
            "saves_count": 0,
            "schema_data": null,
            "shares_count": 0,
            "slug": "join-tables-to-map-userid-to-name",
            "tags": [],
            "title": "Join tables to map userId to name",
            "total_likes": 0,
            "updated_at": "2026-01-24T03:47:37.433568",
            "user_id": 1,
            "views_count": 0
        },
        {
            "ai_comments_count": 0,
            "ai_likes_count": 0,
            "author": "admin",
            "categories": [],
            "category": "Coding & Algorithms",
            "category_raw": "Coding & Algorithms",
            "comments": [],
            "comments_count": 0,
            "company": "Airbnb",
            "content": "本帖最后由 毒奶当 于 2026-1-20 22:07 编辑\n楼主充分准备了Airbnb有一段时间，从论坛也获取到了很多信息，但很遗憾最终并没有通过面试。发出面经留给未来要面试的朋友，包括我对面试fail的一些思考，顺便攒点大米谢谢大家。\n电面：\nAirbnb经典的booking题目，split stay，地理有太多原题，大家找一下就有了\nOnsite：\n第一轮电面：蠡口伞伞齐\n第二轮电面：给你两个linked list(可能带环)，让你判断两个linked list是否有重合的node\nSystem Design：Airbnb经典的聊天系统，对data schema要求比较高，额外要求对topN的group chat做优化。\n深挖简历项目\n和 HR 沟通后得知，这次主要卡在系统设计和简历项目两轮，达到不了对方senior hiring standard。\n我自己复盘下来，其实刚面完的时候感觉还不错。系统设计这轮，问的关键点基本都覆盖到了，包括完整的 schema、high-level design，也讨论了多台 WebSocket 的路由、容灾等问题。\n简历项目这一轮原本是一小时的面试，实际聊了大概一个半小时。我的项目本身比较复杂，也涉及一定的 domain knowledge，面试官对这个领域并不熟，所以最终只深入聊了一个项目。当时聊完的感觉非常不错，但结果还是no positive signal。\n事后反思，可能问题在于：\n系统设计太过专注于设计的正确性，但面试官可能更侧重于两人沟通交流\n一个项目讲得太久，应该控制在 20 分钟以内\n简历项目并不是越复杂越好，更重要的是能否抽象、简化，并在短时间内把事情讲清楚\n就当一次经验教训，move on 了。\n也祝后面继续面试的大家好运，加油！顺便给自己攒点米看面经。",
            "content_enhanced": "You are implementing a simplified **split-stay** search.\n\nYou are given:\n- A desired trip interval **[start, end)**, where dates are represented as integers (e.g., days). The guest stays nights `start, start+1, ..., end-1`.\n- `n` listings. For each listing `i`, you are given a set of **available** (bookable) date intervals `avail[i]`, each as **[li, ri)**. Intervals within a listing are non-overlapping and sorted.\n\nA trip is feasible if it can be covered by:\n1. **One listing** that is available for the entire interval **[start, end)**, OR\n2. **Exactly two listings** `(A, B)` with a single switch day `mid` such that:\n   - Listing `A` covers **[start, mid)**\n   - Listing `B` covers **[mid, end)**\n   - `start < mid < end` (both stays are non-empty)\n   - There are **no gaps** and no overlap requirements beyond continuous coverage.\n\n### Task\nReturn whether the trip is feasible. If feasible, return **one valid plan**:\n- Either `(A)` for a single-listing stay, or\n- `(A, B, mid)` for a split stay.\n\n### Constraints (you may assume)\n- `1 ≤ n ≤ 2e5`\n- Total number of availability intervals across all listings ≤ `2e5`\n- Dates fit in 32-bit signed integers.\n\n### Notes\n- Listings are identified by integer IDs `0..n-1`.\n- Availability intervals are inclusive of `li` and exclusive of `ri`.\n",
            "content_raw": null,
            "created_at": "2026-01-22T00:00:00",
            "difficulty": "hard",
            "has_coding_schema": false,
            "has_schema_data": false,
            "id": 6036,
            "interview_round": "Onsite",
            "is_liked": false,
            "is_locked": true,
            "is_saved": false,
            "is_shared": false,
            "likes": [],
            "likes_count": 0,
            "position": "Software Engineer",
            "real_comments_count": 0,
            "real_likes_count": 0,
            "saves_count": 0,
            "schema_data": null,
            "shares_count": 0,
            "slug": "find-a-split-stay-booking-across-listings",
            "tags": [],
            "title": "Find a split-stay booking across listings",
            "total_likes": 0,
            "updated_at": "2026-01-22T17:11:28.383427",
            "user_id": 1,
            "views_count": 0
        },
        {
            "ai_comments_count": 0,
            "ai_likes_count": 0,
            "author": "admin",
            "categories": [],
            "category": "Coding & Algorithms",
            "category_raw": "Coding & Algorithms",
            "comments": [],
            "comments_count": 0,
            "company": "Airbnb",
            "content": "本帖最后由 毒奶当 于 2026-1-20 22:07 编辑\n楼主充分准备了Airbnb有一段时间，从论坛也获取到了很多信息，但很遗憾最终并没有通过面试。发出面经留给未来要面试的朋友，包括我对面试fail的一些思考，顺便攒点大米谢谢大家。\n电面：\nAirbnb经典的booking题目，split stay，地理有太多原题，大家找一下就有了\nOnsite：\n第一轮电面：蠡口伞伞齐\n第二轮电面：给你两个linked list(可能带环)，让你判断两个linked list是否有重合的node\nSystem Design：Airbnb经典的聊天系统，对data schema要求比较高，额外要求对topN的group chat做优化。\n深挖简历项目\n和 HR 沟通后得知，这次主要卡在系统设计和简历项目两轮，达到不了对方senior hiring standard。\n我自己复盘下来，其实刚面完的时候感觉还不错。系统设计这轮，问的关键点基本都覆盖到了，包括完整的 schema、high-level design，也讨论了多台 WebSocket 的路由、容灾等问题。\n简历项目这一轮原本是一小时的面试，实际聊了大概一个半小时。我的项目本身比较复杂，也涉及一定的 domain knowledge，面试官对这个领域并不熟，所以最终只深入聊了一个项目。当时聊完的感觉非常不错，但结果还是no positive signal。\n事后反思，可能问题在于：\n系统设计太过专注于设计的正确性，但面试官可能更侧重于两人沟通交流\n一个项目讲得太久，应该控制在 20 分钟以内\n简历项目并不是越复杂越好，更重要的是能否抽象、简化，并在短时间内把事情讲清楚\n就当一次经验教训，move on 了。\n也祝后面继续面试的大家好运，加油！顺便给自己攒点米看面经。",
            "content_enhanced": "Given the root of a binary tree where each node contains an integer value (can be 0 or positive), choose a subset of nodes such that **no selected node is directly connected to another selected node** (i.e., you cannot select both a parent and its child).\n\n### Task\nReturn the **maximum possible sum** of the selected node values.\n\n### Input\n- `root`: root node of a binary tree.\n\n### Output\n- An integer: the maximum sum under the constraint.\n\n### Constraints (typical)\n- Up to `1e5` nodes.\n- Tree is not necessarily balanced.\n",
            "content_raw": null,
            "created_at": "2026-01-22T00:00:00",
            "difficulty": "hard",
            "has_coding_schema": false,
            "has_schema_data": false,
            "id": 6037,
            "interview_round": "Onsite",
            "is_liked": false,
            "is_locked": true,
            "is_saved": false,
            "is_shared": false,
            "likes": [],
            "likes_count": 0,
            "position": "Software Engineer",
            "real_comments_count": 0,
            "real_likes_count": 0,
            "saves_count": 0,
            "schema_data": null,
            "shares_count": 0,
            "slug": "maximize-sum-with-no-adjacent-tree-nodes",
            "tags": [],
            "title": "Maximize sum with no adjacent tree nodes",
            "total_likes": 0,
            "updated_at": "2026-01-22T17:11:28.383477",
            "user_id": 1,
            "views_count": 0
        },
        {
            "ai_comments_count": 0,
            "ai_likes_count": 0,
            "author": "admin",
            "categories": [],
            "category": "Coding & Algorithms",
            "category_raw": "Coding & Algorithms",
            "comments": [],
            "comments_count": 0,
            "company": "Airbnb",
            "content": "本帖最后由 毒奶当 于 2026-1-20 22:07 编辑\n楼主充分准备了Airbnb有一段时间，从论坛也获取到了很多信息，但很遗憾最终并没有通过面试。发出面经留给未来要面试的朋友，包括我对面试fail的一些思考，顺便攒点大米谢谢大家。\n电面：\nAirbnb经典的booking题目，split stay，地理有太多原题，大家找一下就有了\nOnsite：\n第一轮电面：蠡口伞伞齐\n第二轮电面：给你两个linked list(可能带环)，让你判断两个linked list是否有重合的node\nSystem Design：Airbnb经典的聊天系统，对data schema要求比较高，额外要求对topN的group chat做优化。\n深挖简历项目\n和 HR 沟通后得知，这次主要卡在系统设计和简历项目两轮，达到不了对方senior hiring standard。\n我自己复盘下来，其实刚面完的时候感觉还不错。系统设计这轮，问的关键点基本都覆盖到了，包括完整的 schema、high-level design，也讨论了多台 WebSocket 的路由、容灾等问题。\n简历项目这一轮原本是一小时的面试，实际聊了大概一个半小时。我的项目本身比较复杂，也涉及一定的 domain knowledge，面试官对这个领域并不熟，所以最终只深入聊了一个项目。当时聊完的感觉非常不错，但结果还是no positive signal。\n事后反思，可能问题在于：\n系统设计太过专注于设计的正确性，但面试官可能更侧重于两人沟通交流\n一个项目讲得太久，应该控制在 20 分钟以内\n简历项目并不是越复杂越好，更重要的是能否抽象、简化，并在短时间内把事情讲清楚\n就当一次经验教训，move on 了。\n也祝后面继续面试的大家好运，加油！顺便给自己攒点米看面经。",
            "content_enhanced": "You are given the heads of two singly linked lists `headA` and `headB`.\n\nEach list may be:\n- A standard acyclic linked list, or\n- A cyclic linked list (contains a loop).\n\nNodes are compared by **reference identity** (i.e., the same node object in memory), not by value.\n\n### Task\nDetermine whether the two lists **overlap** (share at least one common node). Return `true` if they overlap, otherwise return `false`.\n\n### Follow-up\nIf they do overlap, you may optionally return **any one** shared node.\n\n### Constraints (typical)\n- `O(1)` extra space preferred.\n- Aim for `O(m + n)` time.\n",
            "content_raw": null,
            "created_at": "2026-01-22T00:00:00",
            "difficulty": "hard",
            "has_coding_schema": false,
            "has_schema_data": false,
            "id": 6038,
            "interview_round": "Onsite",
            "is_liked": false,
            "is_locked": true,
            "is_saved": false,
            "is_shared": false,
            "likes": [],
            "likes_count": 0,
            "position": "Software Engineer",
            "real_comments_count": 0,
            "real_likes_count": 0,
            "saves_count": 0,
            "schema_data": null,
            "shares_count": 0,
            "slug": "detect-overlap-of-two-linked-lists-with-cycles",
            "tags": [],
            "title": "Detect overlap of two linked lists with cycles",
            "total_likes": 0,
            "updated_at": "2026-01-22T17:11:28.383496",
            "user_id": 1,
            "views_count": 0
        },
        {
            "ai_comments_count": 0,
            "ai_likes_count": 0,
            "author": "admin",
            "categories": [],
            "category": "Coding & Algorithms",
            "category_raw": "Coding & Algorithms",
            "comments": [],
            "comments_count": 0,
            "company": "Netflix",
            "content": "本帖最后由 匿名 于 2026-1-21 13:24 编辑\n首先声明：本文是AI根据我写的草稿生成的\n先说结论：我挂了。挂完的第一反应是“我是不是真的挂得有点委屈？”于是把整个过程写详细一些，代码、思路、沟通、踩坑，都摊开给大家看，欢迎拍砖。\n---\n## TPS（Technical Problem Solving）轮：题目澄清反复、时间不够用\n- 时长：~60min\n- 结果：挂\n- 反馈：Need to collaborate more（多协作）\n### 题目（我理解的版本在变化）\nnetlifx home page has a list of shelf，每个 shelf 有一堆 title。要在 viewport（每个 shelf 最多显示 X 个）里做dedupe。垂直滚动我们先不管（vertical viewport 视为无限）。\n### 我的推进过程（v1 → v5）\n#### v1：全局去重（拿到口头确认后开写）\n当时我问了不少问题，面试官说 OK，我就开始写。结果写完发现他要的不是这个……\n```python\ndef dedupe_v1(titles: list[list[int]], x: int):\nvisited = set()\nret = []\nfor shelf in titles:\ncurrent = []\nfor title in shelf:\nif title not in visited:\ncurrent.append(title)\nvisited.add(title)\nret.append(current)\nreturn ret\n```\n#### v2：只在前 X 个 unique 里全局去重（还是不对）\n```python\ndef dedupe_v2(titles: list[list[int]], x: int):\nvisited = set()\nret = []\nfor shelf in titles:\ncurrent = []\nfor title in shelf:\nif len(visited) <= x and title not in visited:\ncurrent.append(title)\nvisited.add(title)\nelif len(visited) > x:\ncurrent.append(title)\nret.append(current)\nreturn ret\n```\n#### v3：前 X 位跨 shelf 去重，之后只在各自 shelf 内去重（思路对，但实现有坑）\n```python\ndef dedupe_v3(titles: list[list[int]], x: int):\nvisited = set()\nret = []\nfor shelf in titles:\ncurrent = []\nlocal = set()\nfor title in shelf:\nif len(current) < x:\nif title not in visited:\ncurrent.append(title)\nvisited.add(title)  # 少了把前 X 位加入 local 的步骤\nelse:\nif title not in local:\ncurrent.append(title)\nlocal.add(title)\nret.append(current)\nreturn ret\n```\n#### v4：最后 5 分钟Fix版（能跑但 if/else 很乱）\n```python\ndef dedupe_v4(titles: list[list[int]], x: int):\nvisited = set()\nret = []\nfor shelf in titles:\ncurrent = []\nlocal = set()\nfor title in shelf:\ndedupe = False\nif len(current) < x:\nif title not in visited:\ncurrent.append(title)\nvisited.add(title)\nelse:\ndedupe = True\nelse:\nif title not in local:\ncurrent.append(title)\nif not dedupe:\nlocal.add(title)\nret.append(current)\nreturn ret\n```\n#### v5：面试后整理出的 clean 版本（结构清晰）\n```python\ndef dedupe_v5(titles: list[list[int]], x: int):\nglobal_visited = set()\nret = []\nfor shelf in titles:\ncurrent = []\nlocal_visited = set()\nfor title in shelf:\nif len(current) < x and title not in global_visited:\ncurrent.append(title)\nglobal_visited.add(title)\nlocal_visited.add(title)\nelif len(current) >= x and title not in local_visited:\ncurrent.append(title)\nlocal_visited.add(title)\nret.append(current)\nreturn ret\n```\n### 我的反思（TPS）\n- 我确实有在问问题、拿确认，但还是三次理解偏差；说明我的提问方式和确认方式可以再优化（比如举具体 counterexample 让对方否定/肯定）。\n- 时间被来回澄清吃掉，最后 5 分钟压出来的 v4 肯定不够 clean。\n- “Need to collaborate more” 很可能指的是：更主动用例驱动对齐需求、边画边说、让对方看到你的思考分支，而不是“拿到一句口头确认就开写”。\n---\n## Coding 轮：第一题顺利，第二题在压力下写得不够简洁\n- 时长：~60min\n- 结果：挂\n- 反馈：Code could be more concise/cleaner\n### 问题 1：最大连续相同 show 的长度（15 分钟、一次过）\n```python\ndef max_consecutive_streak(shows: list[int]) -> int:\nleft = 0\nmax_streak = 0\nfor right in range(len(shows)):\nwhile shows[right] != shows[left]:\nleft += 1\nmax_streak = max(max_streak, right - left + 1)\nreturn max_streak\n```\n### 问题 2：最长连续不重复子数组（现场最终版过测，但不够“clean”）\n先写了一个有 bug 的版本：\n```python\ndef max_consecutive_unique_shows_with_bug(shows: list[int]) -> list[int]:\nleft = 0\nret = []\nvisited = set()\nfor right in range(len(shows)):\nvisited.add(shows[right])\nwhile shows[right] in visited:\nvisited.remove(shows[left])\nleft += 1\nif right - left + 1 > len(ret):\nret = shows[left:right + 1]\nreturn ret\n```\n当场我问“要不要手算还是直接线上 debug”，对方说都行；于是我线上 debug，定位到 bug（先 add 再检查）。\n在时间压力下，我用了 dictionary 计数的思路，正确但不够简洁：\n```python\ndef max_consecutive_unique_shows_with_final(shows: list[int]) -> list[int]:\nleft = 0\nmax_len = 0\nret = []\nvisited = dict()\nfor right in range(len(shows)):\ncur = shows[right]\nwhile visited.get(cur, 0) > 0:\nvisited[shows[left]] -= 1\nleft += 1\nvisited[shows[right]] = 1\nwindow_len = right - left + 1\nif window_len > max_len:\nmax_len = window_len\nret = shows[left:right + 1]\nreturn ret\n```\n更简洁的 set 解法（当时没想出来，但之后写了）：\n```python\ndef max_consecutive_unique_shows(shows: list[int]) -> list[int]:\nleft = 0\nret = []\nvisited = set()\nfor right in range(len(shows)):\nwhile shows[right] in visited:\nvisited.remove(shows[left])\nleft += 1\nvisited.add(shows[right])\nif right - left + 1 > len(ret):\nret = shows[left:right + 1]\nreturn ret\n```\n最优的跳指针（post-interview by AI）：\n```python\ndef max_consecutive_unique_shows_optimal(shows: list[int]) -> list[int]:\nleft = 0\nret = []\nvisited = dict()\nfor right in range(len(shows)):\ncur = shows[right]\nif cur in visited and visited[cur] >= left:\nleft = visited[cur] + 1\nvisited[cur] = right\nif right - left + 1 > len(ret):\nret = shows[left:right + 1]\nreturn ret\n```\n### 我的反思（Coding）\n- 我选择了能保证正确性的 dictionary 版本，确实不如 set 简洁；在压力下优先稳是本能，但从“代码美感/简洁性”的角度不加分。\n- 面试问“还能不能更好”，我应该把 set 版也写出来（即使晚几分钟），或者先用口头把 set 的思路讲清楚再动手。\n---\n## 我觉得可能委屈的点 & 想请大家评价\n- TPS 我确实有问、有确认，但仍然多次误解；是不是应该用更强的“Example oriented clarification”来合作（collaborate）？\n- Coding 第二题我在时间压力下交付了正确、O(n)、可读的解，但不够“clean”；这种情况下该不该挂？\n- 如果你是面试官，你会怎么打分？ 是不是Netflix bar很高？",
            "content_enhanced": "You are rendering a streaming app home page.\n\n- The home page consists of **shelves** displayed from top to bottom.\n- Each shelf contains a list of `titleId` values (integers).\n- Each shelf’s horizontal viewport can show at most **X** titles.\n- Assume the vertical viewport is unlimited (i.e., you process shelves in order, top to bottom).\n\nImplement a function that **filters titles while preserving order** under the following deduplication rules:\n\n1. **Global dedupe within the visible region:**\n   - While building the **first `X` output titles** for a shelf, you must **skip** any `titleId` that has already appeared in the **visible region** (first `X` output titles) of any earlier shelf.\n2. **Local dedupe after the visible region:**\n   - After a shelf has already produced `X` output titles, continue outputting additional titles from that shelf, but now **only dedupe within the same shelf** (i.e., skip repeats that have already been output in this shelf).\n   - Global deduplication no longer applies past position `X` within a shelf.\n\n### Function signature\n- Input: `shelves: List[List[int]]`, `X: int`\n- Output: `List[List[int]]` (the filtered shelves)\n\n### Notes\n- Preserve the original relative order of titles within each shelf.\n- If a shelf has fewer than `X` eligible titles (after global dedupe), it may output fewer than `X` titles.\n\n### Example\nIf `X = 2` and shelves are:\n\n- Shelf 1: `[1, 2, 1, 3]`\n- Shelf 2: `[2, 4, 2, 5]`\n\nThen:\n- Shelf 1 visible region (first 2 outputs) becomes `[1, 2]` (global seen = `{1,2}`), then locally can output `3` (skipping the repeated `1`).\n- Shelf 2 visible region cannot use `2` (already globally visible), so it outputs `[4, 2]` as its first 2 outputs (4 is new globally visible; once the shelf has hit `X` outputs, `2` is allowed even though it was globally visible). After that it can output `5`.\n\nSo the output is `[[1, 2, 3], [4, 2, 5]]`.\n\nSpecify and implement the algorithm.",
            "content_raw": null,
            "created_at": "2026-01-22T00:00:00",
            "difficulty": "medium",
            "has_coding_schema": false,
            "has_schema_data": false,
            "id": 6040,
            "interview_round": "Technical Screen",
            "is_liked": false,
            "is_locked": true,
            "is_saved": false,
            "is_shared": false,
            "likes": [],
            "likes_count": 0,
            "position": "Software Engineer",
            "real_comments_count": 0,
            "real_likes_count": 0,
            "saves_count": 0,
            "schema_data": null,
            "shares_count": 0,
            "slug": "dedupe-titles-in-per-shelf-viewport",
            "tags": [],
            "title": "Dedupe titles in per-shelf viewport",
            "total_likes": 0,
            "updated_at": "2026-01-22T17:12:03.957630",
            "user_id": 1,
            "views_count": 0
        },
        {
            "ai_comments_count": 0,
            "ai_likes_count": 0,
            "author": "admin",
            "categories": [],
            "category": "Coding & Algorithms",
            "category_raw": "Coding & Algorithms",
            "comments": [],
            "comments_count": 0,
            "company": "Netflix",
            "content": "本帖最后由 匿名 于 2026-1-21 13:24 编辑\n首先声明：本文是AI根据我写的草稿生成的\n先说结论：我挂了。挂完的第一反应是“我是不是真的挂得有点委屈？”于是把整个过程写详细一些，代码、思路、沟通、踩坑，都摊开给大家看，欢迎拍砖。\n---\n## TPS（Technical Problem Solving）轮：题目澄清反复、时间不够用\n- 时长：~60min\n- 结果：挂\n- 反馈：Need to collaborate more（多协作）\n### 题目（我理解的版本在变化）\nnetlifx home page has a list of shelf，每个 shelf 有一堆 title。要在 viewport（每个 shelf 最多显示 X 个）里做dedupe。垂直滚动我们先不管（vertical viewport 视为无限）。\n### 我的推进过程（v1 → v5）\n#### v1：全局去重（拿到口头确认后开写）\n当时我问了不少问题，面试官说 OK，我就开始写。结果写完发现他要的不是这个……\n```python\ndef dedupe_v1(titles: list[list[int]], x: int):\nvisited = set()\nret = []\nfor shelf in titles:\ncurrent = []\nfor title in shelf:\nif title not in visited:\ncurrent.append(title)\nvisited.add(title)\nret.append(current)\nreturn ret\n```\n#### v2：只在前 X 个 unique 里全局去重（还是不对）\n```python\ndef dedupe_v2(titles: list[list[int]], x: int):\nvisited = set()\nret = []\nfor shelf in titles:\ncurrent = []\nfor title in shelf:\nif len(visited) <= x and title not in visited:\ncurrent.append(title)\nvisited.add(title)\nelif len(visited) > x:\ncurrent.append(title)\nret.append(current)\nreturn ret\n```\n#### v3：前 X 位跨 shelf 去重，之后只在各自 shelf 内去重（思路对，但实现有坑）\n```python\ndef dedupe_v3(titles: list[list[int]], x: int):\nvisited = set()\nret = []\nfor shelf in titles:\ncurrent = []\nlocal = set()\nfor title in shelf:\nif len(current) < x:\nif title not in visited:\ncurrent.append(title)\nvisited.add(title)  # 少了把前 X 位加入 local 的步骤\nelse:\nif title not in local:\ncurrent.append(title)\nlocal.add(title)\nret.append(current)\nreturn ret\n```\n#### v4：最后 5 分钟Fix版（能跑但 if/else 很乱）\n```python\ndef dedupe_v4(titles: list[list[int]], x: int):\nvisited = set()\nret = []\nfor shelf in titles:\ncurrent = []\nlocal = set()\nfor title in shelf:\ndedupe = False\nif len(current) < x:\nif title not in visited:\ncurrent.append(title)\nvisited.add(title)\nelse:\ndedupe = True\nelse:\nif title not in local:\ncurrent.append(title)\nif not dedupe:\nlocal.add(title)\nret.append(current)\nreturn ret\n```\n#### v5：面试后整理出的 clean 版本（结构清晰）\n```python\ndef dedupe_v5(titles: list[list[int]], x: int):\nglobal_visited = set()\nret = []\nfor shelf in titles:\ncurrent = []\nlocal_visited = set()\nfor title in shelf:\nif len(current) < x and title not in global_visited:\ncurrent.append(title)\nglobal_visited.add(title)\nlocal_visited.add(title)\nelif len(current) >= x and title not in local_visited:\ncurrent.append(title)\nlocal_visited.add(title)\nret.append(current)\nreturn ret\n```\n### 我的反思（TPS）\n- 我确实有在问问题、拿确认，但还是三次理解偏差；说明我的提问方式和确认方式可以再优化（比如举具体 counterexample 让对方否定/肯定）。\n- 时间被来回澄清吃掉，最后 5 分钟压出来的 v4 肯定不够 clean。\n- “Need to collaborate more” 很可能指的是：更主动用例驱动对齐需求、边画边说、让对方看到你的思考分支，而不是“拿到一句口头确认就开写”。\n---\n## Coding 轮：第一题顺利，第二题在压力下写得不够简洁\n- 时长：~60min\n- 结果：挂\n- 反馈：Code could be more concise/cleaner\n### 问题 1：最大连续相同 show 的长度（15 分钟、一次过）\n```python\ndef max_consecutive_streak(shows: list[int]) -> int:\nleft = 0\nmax_streak = 0\nfor right in range(len(shows)):\nwhile shows[right] != shows[left]:\nleft += 1\nmax_streak = max(max_streak, right - left + 1)\nreturn max_streak\n```\n### 问题 2：最长连续不重复子数组（现场最终版过测，但不够“clean”）\n先写了一个有 bug 的版本：\n```python\ndef max_consecutive_unique_shows_with_bug(shows: list[int]) -> list[int]:\nleft = 0\nret = []\nvisited = set()\nfor right in range(len(shows)):\nvisited.add(shows[right])\nwhile shows[right] in visited:\nvisited.remove(shows[left])\nleft += 1\nif right - left + 1 > len(ret):\nret = shows[left:right + 1]\nreturn ret\n```\n当场我问“要不要手算还是直接线上 debug”，对方说都行；于是我线上 debug，定位到 bug（先 add 再检查）。\n在时间压力下，我用了 dictionary 计数的思路，正确但不够简洁：\n```python\ndef max_consecutive_unique_shows_with_final(shows: list[int]) -> list[int]:\nleft = 0\nmax_len = 0\nret = []\nvisited = dict()\nfor right in range(len(shows)):\ncur = shows[right]\nwhile visited.get(cur, 0) > 0:\nvisited[shows[left]] -= 1\nleft += 1\nvisited[shows[right]] = 1\nwindow_len = right - left + 1\nif window_len > max_len:\nmax_len = window_len\nret = shows[left:right + 1]\nreturn ret\n```\n更简洁的 set 解法（当时没想出来，但之后写了）：\n```python\ndef max_consecutive_unique_shows(shows: list[int]) -> list[int]:\nleft = 0\nret = []\nvisited = set()\nfor right in range(len(shows)):\nwhile shows[right] in visited:\nvisited.remove(shows[left])\nleft += 1\nvisited.add(shows[right])\nif right - left + 1 > len(ret):\nret = shows[left:right + 1]\nreturn ret\n```\n最优的跳指针（post-interview by AI）：\n```python\ndef max_consecutive_unique_shows_optimal(shows: list[int]) -> list[int]:\nleft = 0\nret = []\nvisited = dict()\nfor right in range(len(shows)):\ncur = shows[right]\nif cur in visited and visited[cur] >= left:\nleft = visited[cur] + 1\nvisited[cur] = right\nif right - left + 1 > len(ret):\nret = shows[left:right + 1]\nreturn ret\n```\n### 我的反思（Coding）\n- 我选择了能保证正确性的 dictionary 版本，确实不如 set 简洁；在压力下优先稳是本能，但从“代码美感/简洁性”的角度不加分。\n- 面试问“还能不能更好”，我应该把 set 版也写出来（即使晚几分钟），或者先用口头把 set 的思路讲清楚再动手。\n---\n## 我觉得可能委屈的点 & 想请大家评价\n- TPS 我确实有问、有确认，但仍然多次误解；是不是应该用更强的“Example oriented clarification”来合作（collaborate）？\n- Coding 第二题我在时间压力下交付了正确、O(n)、可读的解，但不够“clean”；这种情况下该不该挂？\n- 如果你是面试官，你会怎么打分？ 是不是Netflix bar很高？",
            "content_enhanced": "Given an array `shows` of integers, find the **maximum length of a contiguous run** where all values are equal.\n\n### Function signature\n- Input: `shows: List[int]`\n- Output: `int`\n\n### Examples\n- `shows = [7, 7, 2, 2, 2, 7]` → `3` (the run `[2,2,2]`)\n- `shows = []` → `0`\n\n### Constraints\n- Aim for an `O(n)` time solution with `O(1)` extra space.",
            "content_raw": null,
            "created_at": "2026-01-22T00:00:00",
            "difficulty": "medium",
            "has_coding_schema": false,
            "has_schema_data": false,
            "id": 6041,
            "interview_round": "Technical Screen",
            "is_liked": false,
            "is_locked": true,
            "is_saved": false,
            "is_shared": false,
            "likes": [],
            "likes_count": 0,
            "position": "Software Engineer",
            "real_comments_count": 0,
            "real_likes_count": 0,
            "saves_count": 0,
            "schema_data": null,
            "shares_count": 0,
            "slug": "find-longest-run-of-identical-consecutive-shows",
            "tags": [],
            "title": "Find longest run of identical consecutive shows",
            "total_likes": 0,
            "updated_at": "2026-01-22T17:12:03.957669",
            "user_id": 1,
            "views_count": 0
        },
        {
            "ai_comments_count": 0,
            "ai_likes_count": 0,
            "author": "admin",
            "categories": [],
            "category": "Coding & Algorithms",
            "category_raw": "Coding & Algorithms",
            "comments": [],
            "comments_count": 0,
            "company": "Netflix",
            "content": "本帖最后由 匿名 于 2026-1-21 13:24 编辑\n首先声明：本文是AI根据我写的草稿生成的\n先说结论：我挂了。挂完的第一反应是“我是不是真的挂得有点委屈？”于是把整个过程写详细一些，代码、思路、沟通、踩坑，都摊开给大家看，欢迎拍砖。\n---\n## TPS（Technical Problem Solving）轮：题目澄清反复、时间不够用\n- 时长：~60min\n- 结果：挂\n- 反馈：Need to collaborate more（多协作）\n### 题目（我理解的版本在变化）\nnetlifx home page has a list of shelf，每个 shelf 有一堆 title。要在 viewport（每个 shelf 最多显示 X 个）里做dedupe。垂直滚动我们先不管（vertical viewport 视为无限）。\n### 我的推进过程（v1 → v5）\n#### v1：全局去重（拿到口头确认后开写）\n当时我问了不少问题，面试官说 OK，我就开始写。结果写完发现他要的不是这个……\n```python\ndef dedupe_v1(titles: list[list[int]], x: int):\nvisited = set()\nret = []\nfor shelf in titles:\ncurrent = []\nfor title in shelf:\nif title not in visited:\ncurrent.append(title)\nvisited.add(title)\nret.append(current)\nreturn ret\n```\n#### v2：只在前 X 个 unique 里全局去重（还是不对）\n```python\ndef dedupe_v2(titles: list[list[int]], x: int):\nvisited = set()\nret = []\nfor shelf in titles:\ncurrent = []\nfor title in shelf:\nif len(visited) <= x and title not in visited:\ncurrent.append(title)\nvisited.add(title)\nelif len(visited) > x:\ncurrent.append(title)\nret.append(current)\nreturn ret\n```\n#### v3：前 X 位跨 shelf 去重，之后只在各自 shelf 内去重（思路对，但实现有坑）\n```python\ndef dedupe_v3(titles: list[list[int]], x: int):\nvisited = set()\nret = []\nfor shelf in titles:\ncurrent = []\nlocal = set()\nfor title in shelf:\nif len(current) < x:\nif title not in visited:\ncurrent.append(title)\nvisited.add(title)  # 少了把前 X 位加入 local 的步骤\nelse:\nif title not in local:\ncurrent.append(title)\nlocal.add(title)\nret.append(current)\nreturn ret\n```\n#### v4：最后 5 分钟Fix版（能跑但 if/else 很乱）\n```python\ndef dedupe_v4(titles: list[list[int]], x: int):\nvisited = set()\nret = []\nfor shelf in titles:\ncurrent = []\nlocal = set()\nfor title in shelf:\ndedupe = False\nif len(current) < x:\nif title not in visited:\ncurrent.append(title)\nvisited.add(title)\nelse:\ndedupe = True\nelse:\nif title not in local:\ncurrent.append(title)\nif not dedupe:\nlocal.add(title)\nret.append(current)\nreturn ret\n```\n#### v5：面试后整理出的 clean 版本（结构清晰）\n```python\ndef dedupe_v5(titles: list[list[int]], x: int):\nglobal_visited = set()\nret = []\nfor shelf in titles:\ncurrent = []\nlocal_visited = set()\nfor title in shelf:\nif len(current) < x and title not in global_visited:\ncurrent.append(title)\nglobal_visited.add(title)\nlocal_visited.add(title)\nelif len(current) >= x and title not in local_visited:\ncurrent.append(title)\nlocal_visited.add(title)\nret.append(current)\nreturn ret\n```\n### 我的反思（TPS）\n- 我确实有在问问题、拿确认，但还是三次理解偏差；说明我的提问方式和确认方式可以再优化（比如举具体 counterexample 让对方否定/肯定）。\n- 时间被来回澄清吃掉，最后 5 分钟压出来的 v4 肯定不够 clean。\n- “Need to collaborate more” 很可能指的是：更主动用例驱动对齐需求、边画边说、让对方看到你的思考分支，而不是“拿到一句口头确认就开写”。\n---\n## Coding 轮：第一题顺利，第二题在压力下写得不够简洁\n- 时长：~60min\n- 结果：挂\n- 反馈：Code could be more concise/cleaner\n### 问题 1：最大连续相同 show 的长度（15 分钟、一次过）\n```python\ndef max_consecutive_streak(shows: list[int]) -> int:\nleft = 0\nmax_streak = 0\nfor right in range(len(shows)):\nwhile shows[right] != shows[left]:\nleft += 1\nmax_streak = max(max_streak, right - left + 1)\nreturn max_streak\n```\n### 问题 2：最长连续不重复子数组（现场最终版过测，但不够“clean”）\n先写了一个有 bug 的版本：\n```python\ndef max_consecutive_unique_shows_with_bug(shows: list[int]) -> list[int]:\nleft = 0\nret = []\nvisited = set()\nfor right in range(len(shows)):\nvisited.add(shows[right])\nwhile shows[right] in visited:\nvisited.remove(shows[left])\nleft += 1\nif right - left + 1 > len(ret):\nret = shows[left:right + 1]\nreturn ret\n```\n当场我问“要不要手算还是直接线上 debug”，对方说都行；于是我线上 debug，定位到 bug（先 add 再检查）。\n在时间压力下，我用了 dictionary 计数的思路，正确但不够简洁：\n```python\ndef max_consecutive_unique_shows_with_final(shows: list[int]) -> list[int]:\nleft = 0\nmax_len = 0\nret = []\nvisited = dict()\nfor right in range(len(shows)):\ncur = shows[right]\nwhile visited.get(cur, 0) > 0:\nvisited[shows[left]] -= 1\nleft += 1\nvisited[shows[right]] = 1\nwindow_len = right - left + 1\nif window_len > max_len:\nmax_len = window_len\nret = shows[left:right + 1]\nreturn ret\n```\n更简洁的 set 解法（当时没想出来，但之后写了）：\n```python\ndef max_consecutive_unique_shows(shows: list[int]) -> list[int]:\nleft = 0\nret = []\nvisited = set()\nfor right in range(len(shows)):\nwhile shows[right] in visited:\nvisited.remove(shows[left])\nleft += 1\nvisited.add(shows[right])\nif right - left + 1 > len(ret):\nret = shows[left:right + 1]\nreturn ret\n```\n最优的跳指针（post-interview by AI）：\n```python\ndef max_consecutive_unique_shows_optimal(shows: list[int]) -> list[int]:\nleft = 0\nret = []\nvisited = dict()\nfor right in range(len(shows)):\ncur = shows[right]\nif cur in visited and visited[cur] >= left:\nleft = visited[cur] + 1\nvisited[cur] = right\nif right - left + 1 > len(ret):\nret = shows[left:right + 1]\nreturn ret\n```\n### 我的反思（Coding）\n- 我选择了能保证正确性的 dictionary 版本，确实不如 set 简洁；在压力下优先稳是本能，但从“代码美感/简洁性”的角度不加分。\n- 面试问“还能不能更好”，我应该把 set 版也写出来（即使晚几分钟），或者先用口头把 set 的思路讲清楚再动手。\n---\n## 我觉得可能委屈的点 & 想请大家评价\n- TPS 我确实有问、有确认，但仍然多次误解；是不是应该用更强的“Example oriented clarification”来合作（collaborate）？\n- Coding 第二题我在时间压力下交付了正确、O(n)、可读的解，但不够“clean”；这种情况下该不该挂？\n- 如果你是面试官，你会怎么打分？ 是不是Netflix bar很高？",
            "content_enhanced": "Given an array `shows` of integers, return the **longest contiguous subarray** in which all values are **distinct** (no repeats within the subarray).\n\n### Function signature\n- Input: `shows: List[int]`\n- Output: `List[int]` (the subarray values)\n\n### Tie-breaking\nIf multiple subarrays have the same maximum length, return the one with the **smallest starting index**.\n\n### Examples\n- `shows = [1, 2, 3, 2, 4]` → `[1, 2, 3]`\n- `shows = [5, 5, 5]` → `[5]`\n- `shows = []` → `[]`\n\n### Constraints\n- Target `O(n)` time.\n- Extra space up to `O(n)` is allowed.",
            "content_raw": null,
            "created_at": "2026-01-22T00:00:00",
            "difficulty": "medium",
            "has_coding_schema": false,
            "has_schema_data": false,
            "id": 6042,
            "interview_round": "Technical Screen",
            "is_liked": false,
            "is_locked": true,
            "is_saved": false,
            "is_shared": false,
            "likes": [],
            "likes_count": 0,
            "position": "Software Engineer",
            "real_comments_count": 0,
            "real_likes_count": 0,
            "saves_count": 0,
            "schema_data": null,
            "shares_count": 0,
            "slug": "return-the-longest-contiguous-subarray-with-all-distinct-values",
            "tags": [],
            "title": "Return the longest contiguous subarray with all distinct values",
            "total_likes": 0,
            "updated_at": "2026-01-22T17:12:03.957688",
            "user_id": 1,
            "views_count": 0
        },
        {
            "ai_comments_count": 0,
            "ai_likes_count": 0,
            "author": "admin",
            "categories": [],
            "category": "Coding & Algorithms",
            "category_raw": "Coding & Algorithms",
            "comments": [],
            "comments_count": 0,
            "company": "Salesforce",
            "content": "链表去重\n出字符串 x 的一个最长子序列，同时该子序列必须是字符串 y 的子串。",
            "content_enhanced": "You are given two independent coding tasks.\n\n## Task 1: Remove duplicates from a linked list\nGiven the head of a **singly linked list** (not necessarily sorted), remove duplicate values so that **each value appears only once**, keeping the **first occurrence** of each value and **preserving the original relative order** of the remaining nodes.\n\n- **Input:** `head` of a singly linked list where each node has fields `val` and `next`.\n- **Output:** the head of the de-duplicated linked list.\n- **Constraints (example):** number of nodes `n` up to `10^5`; node values fit in 32-bit signed int.\n\n**Example**\n- Input: `1 -> 3 -> 1 -> 2 -> 3 -> null`\n- Output: `1 -> 3 -> 2 -> null`\n\n## Task 2: Longest subsequence of x that is a substring of y\nGiven two strings `x` and `y`, find **one** longest string `s` such that:\n\n1. `s` is a **subsequence** of `x` (characters chosen in order, not necessarily contiguous), and\n2. `s` is a **substring** of `y` (contiguous segment of `y`).\n\nIf multiple answers have the same maximum length, you may return **any one** of them.\n\n- **Input:** strings `x`, `y`\n- **Output:** a string `s` meeting the conditions with maximum possible length (or an empty string if no non-empty solution exists).\n- **Constraints (example):** `1 ≤ |x|, |y| ≤ 2000`; characters are lowercase English letters.\n\n**Example**\n- `x = \"abac\"`, `y = \"zzbaczz\"`\n- One valid output: `\"bac\"` (it is a subsequence of `x` and a substring of `y`).\n",
            "content_raw": null,
            "created_at": "2026-01-22T00:00:00",
            "difficulty": "easy",
            "has_coding_schema": false,
            "has_schema_data": false,
            "id": 6048,
            "interview_round": "Take-home Project",
            "is_liked": false,
            "is_locked": true,
            "is_saved": false,
            "is_shared": false,
            "likes": [],
            "likes_count": 0,
            "position": "Software Engineer",
            "real_comments_count": 0,
            "real_likes_count": 0,
            "saves_count": 0,
            "schema_data": null,
            "shares_count": 0,
            "slug": "remove-duplicates-and-find-constrained-longest-subsequence",
            "tags": [],
            "title": "Remove duplicates and find constrained longest subsequence",
            "total_likes": 0,
            "updated_at": "2026-01-22T17:16:03.044611",
            "user_id": 1,
            "views_count": 0
        },
        {
            "ai_comments_count": 0,
            "ai_likes_count": 0,
            "author": "admin",
            "categories": [],
            "category": "Coding & Algorithms",
            "category_raw": "Coding & Algorithms",
            "comments": [],
            "comments_count": 0,
            "company": "J.P. Morgan",
            "content": "小莫sde\n店面：题目具体忘了，但是是非常简单的字符串操作，然后问java基础问题，我好几个没答上来但居然让我过了。\n现场4轮\nbq+算法 autocomplete， trie的常见题\nbq+算法 anagram group，问多种做法\n设计选课系统\nbq\n非常中规中矩的面试，题目不难都是常见题，但挂了。可能是参考了店面的结果，当时店面能过我也觉得很惊讶。",
            "content_enhanced": "## Problem: Autocomplete suggestions (Trie)\n\nYou are building an autocomplete feature.\n\n### Input\n- A dictionary of `n` unique words `words[i]` (lowercase a–z).\n- An integer array `freq[i]` where `freq[i]` is the usage count of `words[i]`.\n- Then `q` queries. Each query provides:\n  - a `prefix` string\n  - an integer `k` (number of suggestions requested)\n\n### Output\nFor each query, return up to `k` suggested completions:\n- A completion is any word that starts with `prefix`.\n- Rank by **higher frequency first**.\n- Break ties by **lexicographical order**.\n\n### Follow-up\nSupport updates:\n- Operation `add(word, delta)` increases that word’s frequency by `delta` (word may be new).\n- Queries after updates must reflect the new frequencies.\n\n### Constraints (reasonable interview assumptions)\n- `1 ≤ n, q ≤ 2e5`\n- `1 ≤ |word|, |prefix| ≤ 50`\n- Total characters across all words/queries can be large; solutions should be better than scanning all words per query.\n\nExplain what data structure you would use (e.g., Trie) and implement the required operations.",
            "content_raw": null,
            "created_at": "2026-01-22T00:00:00",
            "difficulty": "easy",
            "has_coding_schema": false,
            "has_schema_data": false,
            "id": 6052,
            "interview_round": "Onsite",
            "is_liked": false,
            "is_locked": true,
            "is_saved": false,
            "is_shared": false,
            "likes": [],
            "likes_count": 0,
            "position": "Software Engineer",
            "real_comments_count": 0,
            "real_likes_count": 0,
            "saves_count": 0,
            "schema_data": null,
            "shares_count": 0,
            "slug": "design-an-autocomplete-suggestions-api",
            "tags": [],
            "title": "Design an autocomplete suggestions API",
            "total_likes": 0,
            "updated_at": "2026-01-22T17:19:26.557830",
            "user_id": 1,
            "views_count": 0
        },
        {
            "ai_comments_count": 0,
            "ai_likes_count": 0,
            "author": "admin",
            "categories": [],
            "category": "Coding & Algorithms",
            "category_raw": "Coding & Algorithms",
            "comments": [],
            "comments_count": 0,
            "company": "J.P. Morgan",
            "content": "小莫sde\n店面：题目具体忘了，但是是非常简单的字符串操作，然后问java基础问题，我好几个没答上来但居然让我过了。\n现场4轮\nbq+算法 autocomplete， trie的常见题\nbq+算法 anagram group，问多种做法\n设计选课系统\nbq\n非常中规中矩的面试，题目不难都是常见题，但挂了。可能是参考了店面的结果，当时店面能过我也觉得很惊讶。",
            "content_enhanced": "## Problem: Group anagrams\n\nGiven an array of strings `strs`, group the strings that are anagrams of each other.\n\nTwo strings are anagrams if they contain the same characters with the same multiplicities (order may differ).\n\n### Input\n- `strs`: array of strings (assume lowercase English letters unless stated otherwise).\n\n### Output\nReturn a list of groups, where each group is a list of strings that are mutual anagrams.\n- The order of groups does not matter.\n- The order of strings inside a group does not matter.\n\n### Constraints (typical)\n- `1 ≤ len(strs) ≤ 1e5`\n- `0 ≤ len(strs[i]) ≤ 100`\n\n### Follow-ups discussed in interview\n- Provide **multiple approaches**, and compare time/space tradeoffs (e.g., sorting-based key vs. character-count key).",
            "content_raw": null,
            "created_at": "2026-01-22T00:00:00",
            "difficulty": "easy",
            "has_coding_schema": false,
            "has_schema_data": false,
            "id": 6053,
            "interview_round": "Onsite",
            "is_liked": false,
            "is_locked": true,
            "is_saved": false,
            "is_shared": false,
            "likes": [],
            "likes_count": 0,
            "position": "Software Engineer",
            "real_comments_count": 0,
            "real_likes_count": 0,
            "saves_count": 0,
            "schema_data": null,
            "shares_count": 0,
            "slug": "group-strings-that-are-anagrams",
            "tags": [],
            "title": "Group strings that are anagrams",
            "total_likes": 0,
            "updated_at": "2026-01-22T17:19:26.557872",
            "user_id": 1,
            "views_count": 0
        },
        {
            "ai_comments_count": 0,
            "ai_likes_count": 0,
            "author": "admin",
            "categories": [],
            "category": "Coding & Algorithms",
            "category_raw": "Coding & Algorithms",
            "comments": [],
            "comments_count": 0,
            "company": "Coinbase",
            "content": "不知道为啥之前的帖子被删了\n以下内容需要积分高于 120 您已经可以浏览\n店面：in memory database，4个followup\nVO：\n第一轮query pagination，只做了一个followup，还挺麻烦的用java写\n第二轮food delivery system，一共有四个followup，最后一个应该是背包问题讲一下思路就行\n第三轮HM 正常BQ",
            "content_enhanced": "You are building a small **in-memory database** that stores rows with the following fields:\n\n- `id` (string, unique)\n- `score` (integer)\n- `payload` (string)\n\nYou need to support a **read API** that returns results in a deterministic order and supports **pagination**.\n\n## Requirements\n1. Store rows in memory (you may assume a single process).\n2. Implement a query that returns all rows with `score >= minScore`.\n3. Results must be sorted by:\n   1) `score` ascending\n   2) `id` ascending (tie-breaker)\n4. Pagination must be **cursor-based** (not offset-based):\n   - The client provides a `cursor` representing “the last row seen”.\n   - The server returns up to `pageSize` rows **after** that cursor, plus a `nextCursor`.\n   - If there are no more rows, `nextCursor = null`.\n\n## Function signature (conceptual)\n- Input: `minScore`, `pageSize`, `cursor` (nullable)\n- Output: `(rows[], nextCursor)`\n\n## Follow-ups\n- How do you encode the cursor so it is stable and unambiguous?\n- How do you avoid duplicates or missing rows across pages when there are many rows with the same `score`?\n- What is the time complexity of your approach, and how would you improve it for large datasets?\n\n## Constraints\n- Up to 1,000,000 rows.\n- `pageSize` up to 1,000.\n- Assume no concurrent writes during a single paginated scan (you can state this assumption explicitly).",
            "content_raw": null,
            "created_at": "2026-01-22T00:00:00",
            "difficulty": "medium",
            "has_coding_schema": false,
            "has_schema_data": false,
            "id": 6055,
            "interview_round": "Technical Screen",
            "is_liked": false,
            "is_locked": true,
            "is_saved": false,
            "is_shared": false,
            "likes": [],
            "likes_count": 0,
            "position": "Software Engineer",
            "real_comments_count": 0,
            "real_likes_count": 0,
            "saves_count": 0,
            "schema_data": null,
            "shares_count": 0,
            "slug": "implement-cursor-based-query-pagination",
            "tags": [],
            "title": "Implement cursor-based query pagination",
            "total_likes": 0,
            "updated_at": "2026-01-22T17:20:39.195666",
            "user_id": 1,
            "views_count": 0
        },
        {
            "ai_comments_count": 0,
            "ai_likes_count": 0,
            "author": "admin",
            "categories": [],
            "category": "Coding & Algorithms",
            "category_raw": "Coding & Algorithms",
            "comments": [],
            "comments_count": 0,
            "company": "Two Sigma",
            "content": "里特扣得121，360\n房价预测题：什么feature相关，什么能用，面试官只懂linear regression 不会用；多讲数据清洗之类的，类似DS\ncore statistic：interviewer直接润了，面试完一个小时出结果\n还是求加米加米加米加米加米",
            "content_enhanced": "## Problem\nYou are given an integer array `prices` where `prices[i]` is the price of a stock on day `i`.\n\nYou may complete **at most one transaction**: choose a day to buy one share and a later day to sell that share.\n\nReturn the **maximum profit** you can achieve. If no profit is possible, return `0`.\n\n### Input\n- `prices`: array of integers, length `n`\n\n### Output\n- An integer: maximum achievable profit\n\n### Constraints\n- `1 <= n <= 2 * 10^5`\n- `0 <= prices[i] <= 10^9`\n\n### Example\n- Input: `prices = [7,1,5,3,6,4]`\n- Output: `5` (buy at `1`, sell at `6`)",
            "content_raw": null,
            "created_at": "2026-01-22T00:00:00",
            "difficulty": "nan",
            "has_coding_schema": false,
            "has_schema_data": false,
            "id": 6066,
            "interview_round": "Technical Screen",
            "is_liked": false,
            "is_locked": true,
            "is_saved": false,
            "is_shared": false,
            "likes": [],
            "likes_count": 0,
            "position": "Data Scientist",
            "real_comments_count": 0,
            "real_likes_count": 0,
            "saves_count": 0,
            "schema_data": null,
            "shares_count": 0,
            "slug": "maximize-profit-from-one-stock-trade",
            "tags": [],
            "title": "Maximize profit from one stock trade",
            "total_likes": 0,
            "updated_at": "2026-01-22T17:24:57.845720",
            "user_id": 1,
            "views_count": 0
        },
        {
            "ai_comments_count": 0,
            "ai_likes_count": 0,
            "author": "admin",
            "categories": [],
            "category": "Coding & Algorithms",
            "category_raw": "Coding & Algorithms",
            "comments": [],
            "comments_count": 0,
            "company": "Two Sigma",
            "content": "里特扣得121，360\n房价预测题：什么feature相关，什么能用，面试官只懂linear regression 不会用；多讲数据清洗之类的，类似DS\ncore statistic：interviewer直接润了，面试完一个小时出结果\n还是求加米加米加米加米加米",
            "content_enhanced": "## Problem\nYou are given a sorted integer array `nums` (non-decreasing order) and integers `a`, `b`, `c` that define a quadratic function:\n\n\\[\n f(x) = ax^2 + bx + c\n\\]\n\nApply the function to every element in `nums`, producing an array `res[i] = f(nums[i])`. Return `res` in **sorted (non-decreasing) order**.\n\n### Input\n- `nums`: sorted array of integers\n- `a`, `b`, `c`: integers\n\n### Output\n- A sorted array containing `f(x)` for each `x` in `nums`\n\n### Constraints\n- `1 <= len(nums) <= 2 * 10^5`\n- `-10^4 <= nums[i], a, b, c <= 10^4`\n\n### Example\n- Input: `nums = [-4,-2,2,4], a = 1, b = 3, c = 5`\n- Output: `[3,9,15,33]`",
            "content_raw": null,
            "created_at": "2026-01-22T00:00:00",
            "difficulty": "nan",
            "has_coding_schema": false,
            "has_schema_data": false,
            "id": 6067,
            "interview_round": "Technical Screen",
            "is_liked": false,
            "is_locked": true,
            "is_saved": false,
            "is_shared": false,
            "likes": [],
            "likes_count": 0,
            "position": "Data Scientist",
            "real_comments_count": 0,
            "real_likes_count": 0,
            "saves_count": 0,
            "schema_data": null,
            "shares_count": 0,
            "slug": "return-sorted-values-after-quadratic-transform",
            "tags": [],
            "title": "Return sorted values after quadratic transform",
            "total_likes": 0,
            "updated_at": "2026-01-22T17:24:57.845774",
            "user_id": 1,
            "views_count": 0
        },
        {
            "ai_comments_count": 0,
            "ai_likes_count": 0,
            "author": "admin",
            "categories": [],
            "category": "Coding & Algorithms",
            "category_raw": "Coding & Algorithms",
            "comments": [],
            "comments_count": 0,
            "company": "Bloomberg",
            "content": "改编版岛数量，输出改成了每个size的岛一共有多少个\nbe like input [10, 1, 2, 3] - output: [ 2, 0, 5, 0] (size 10 的岛有两个）\n挂掉原因未知。。。",
            "content_enhanced": "You are given a 2D grid of characters `'0'` and `'1'`, where `'1'` represents land and `'0'` represents water. An **island** is a maximal group of horizontally/vertically (4-directionally) adjacent land cells.\n\nThe **size** of an island is the number of land cells in that island.\n\nYou are also given an integer array `queries`, where each element is a size to query.\n\nReturn an integer array `ans` of the same length as `queries`, where `ans[i]` equals the number of islands in the grid whose size is exactly `queries[i]`.\n\n### Example\nIf the grid contains:\n- 2 islands of size 10\n- 0 islands of size 1\n- 5 islands of size 2\n- 0 islands of size 3\n\nThen for `queries = [10, 1, 2, 3]`, return `ans = [2, 0, 5, 0]`.\n\n### Constraints (reasonable interview defaults)\n- `1 <= rows, cols <= 2000` (or smaller depending on the language/time limit)\n- `grid[r][c] ∈ {'0','1'}`\n- `1 <= queries.length <= 2e5`\n- Query sizes are positive integers\n\n### Notes\n- Use 4-directional adjacency only (no diagonals).\n- `queries` may contain duplicates; return counts for each position.",
            "content_raw": null,
            "created_at": "2026-01-22T00:00:00",
            "difficulty": "medium",
            "has_coding_schema": false,
            "has_schema_data": false,
            "id": 6080,
            "interview_round": "Technical Screen",
            "is_liked": false,
            "is_locked": true,
            "is_saved": false,
            "is_shared": false,
            "likes": [],
            "likes_count": 0,
            "position": "Software Engineer",
            "real_comments_count": 0,
            "real_likes_count": 0,
            "saves_count": 0,
            "schema_data": null,
            "shares_count": 0,
            "slug": "count-islands-by-requested-sizes",
            "tags": [],
            "title": "Count islands by requested sizes",
            "total_likes": 0,
            "updated_at": "2026-01-22T17:29:43.943127",
            "user_id": 1,
            "views_count": 0
        },
        {
            "ai_comments_count": 0,
            "ai_likes_count": 0,
            "author": "admin",
            "categories": [],
            "category": "Coding & Algorithms",
            "category_raw": "Coding & Algorithms",
            "comments": [],
            "comments_count": 0,
            "company": "Cloudflare",
            "content": "一轮做题，一轮SD，然后是product behaviour和general BQ。\n实现 rate limit。\n输入是一对 request 和一堆 rule，rule 里面有 filter policy（按照 first name、last name、IP、country 进行过滤）。\n设计一个 log collection system，从多个 edge data center 收集数据，过程中需要加密。\n注意：题目一开始给的信息不多，所以要跟面试官确认使用场景（实时处理？数据仓库存储？SLA 要求？）。\n没有给具体原因，就直接说挂了。",
            "content_enhanced": "## Problem\nDesign and implement a **rule-based rate limiter** that decides whether each incoming request should be **allowed** or **rejected**.\n\nYou are given:\n- A stream of incoming **requests**.\n- A list of **rate limit rules**. Each rule contains:\n  - A **filter policy** that may match on any subset of the following request attributes:\n    - `first_name`\n    - `last_name`\n    - `ip`\n    - `country`\n  - A rate limit: **at most `limit` requests per `window_seconds`** for the matching key.\n\nA request **matches** a rule if all attributes specified in the rule's filter equal the request's corresponding attributes. (Attributes not present in the filter are treated as wildcards.)\n\n### Rule application semantics\n- A request can match **multiple rules**.\n- The request should be **rejected** if it would violate **any** matched rule (i.e., all matched rules must remain within their limits).\n- If a request is rejected, it must **not** consume quota for any rule.\n\n### Input/Output (one possible interface)\nImplement a class/function with an API similar to:\n- `bool allow(Request r, int timestamp_seconds)`\n\nWhere `timestamp_seconds` is non-decreasing across calls.\n\n### Constraints / expectations\n- Number of rules: up to `R`.\n- Number of requests: up to `N`.\n- Aim for efficient per-request processing (better than scanning all historical requests).\n- Handle large cardinality of keys (e.g., many unique IPs).\n\n### Clarifications to confirm with interviewer (if needed)\n- Whether `timestamp_seconds` is strictly increasing or may have ties.\n- Whether rules can be added/removed dynamically or are static.\n- Whether windows are **sliding** windows or **fixed** aligned windows.\n\n## Example (illustrative)\nA rule: filter `{ip=\"1.2.3.4\"}`, limit `5`, window `60` means: for that IP, allow at most 5 requests in any 60-second window (or in the last 60 seconds, depending on window type you confirm).\n\nReturn `true` for allowed, `false` for rejected.",
            "content_raw": null,
            "created_at": "2026-01-22T00:00:00",
            "difficulty": "medium",
            "has_coding_schema": false,
            "has_schema_data": false,
            "id": 6082,
            "interview_round": "Onsite",
            "is_liked": false,
            "is_locked": true,
            "is_saved": false,
            "is_shared": false,
            "likes": [],
            "likes_count": 0,
            "position": "Software Engineer",
            "real_comments_count": 0,
            "real_likes_count": 0,
            "saves_count": 0,
            "schema_data": null,
            "shares_count": 0,
            "slug": "implement-a-rule-based-rate-limiter",
            "tags": [],
            "title": "Implement a rule-based rate limiter",
            "total_likes": 0,
            "updated_at": "2026-01-22T17:31:35.955860",
            "user_id": 1,
            "views_count": 0
        },
        {
            "ai_comments_count": 0,
            "ai_likes_count": 0,
            "author": "admin",
            "categories": [],
            "category": "Coding & Algorithms",
            "category_raw": "Coding & Algorithms",
            "comments": [],
            "comments_count": 0,
            "company": "Databricks",
            "content": "题目：k 阶 Fibonacci tree，左子树是 (k-2)，右子树是 (k-1)。用 preorder 从 root=0 开始给节点编号。给 k 和两个节点 id a,b，求 a 到 b 的路径（输出节点序列/思路即可）。\n思路（不建树）：\n1）先预处理每阶树的节点数 size[k]\nsize[0]=1，size[1]=1\nsize[k] = 1 + size[k-2] + size[k-1]\n2）利用 preorder 的连续区间定位节点在哪个子树\n假设当前子树是 F(k)，根编号是 r：\n左子树根 = r+1，范围是 [r+1, r+size[k-2]]\n右子树根 = r+1+size[k-2]，范围是后面那一段\n写个函数 getPath(k, r, x)：一路判断 x 落左还是右，递归/迭代下去，拿到 root->x 的路径（复杂度 O(k)）\n3）分别拿到 root->a 和 root->b 两条路径，找 LCA（从头一起走，最后一个相同点）\na->b 路径 = a 往上到 LCA + LCA 往下到 b（拼接注意 LCA 不重复）\n复杂度：O(k)，空间 O(k)。\n注意点：区间边界别写错，size 用 long long（k 大可能溢出就提一嘴 BigInt/截断比较）。",
            "content_enhanced": "You are given a recursively defined **Fibonacci tree** `F(k)`:\n\n- `F(0)` is a single node.\n- `F(1)` is a single node.\n- For `k >= 2`, `F(k)` consists of:\n  - a root node,\n  - a left subtree that is `F(k-2)`,\n  - a right subtree that is `F(k-1)`.\n\nAll nodes are labeled with integer IDs using **preorder traversal** (visit root, then left subtree, then right subtree), starting from the root of `F(k)` having ID `0`.\n\nGiven:\n\n- an integer `k`,\n- two node IDs `a` and `b` (guaranteed to be valid IDs within `F(k)`),\n\nreturn the **sequence of node IDs** along the unique simple path from node `a` to node `b` (inclusive).\n\n### Requirements / Constraints\n- You should **not build the explicit tree**.\n- Assume `k` can be large enough that the total number of nodes grows quickly; use 64-bit arithmetic where possible and describe how you would handle potential overflow if needed.\n\n### Example (format only)\nIf the path is `a -> ... -> b`, output something like:\n\n`[a, ..., b]`\n\n(Exact examples are not required; focus on the algorithm and correct path output.)",
            "content_raw": null,
            "created_at": "2026-01-22T00:00:00",
            "difficulty": "hard",
            "has_coding_schema": false,
            "has_schema_data": false,
            "id": 6093,
            "interview_round": "Technical Screen",
            "is_liked": false,
            "is_locked": true,
            "is_saved": false,
            "is_shared": false,
            "likes": [],
            "likes_count": 0,
            "position": "Software Engineer",
            "real_comments_count": 0,
            "real_likes_count": 0,
            "saves_count": 0,
            "schema_data": null,
            "shares_count": 0,
            "slug": "find-path-between-nodes-in-fibonacci-tree",
            "tags": [],
            "title": "Find path between nodes in Fibonacci tree",
            "total_likes": 0,
            "updated_at": "2026-01-22T17:35:28.951281",
            "user_id": 1,
            "views_count": 0
        },
        {
            "ai_comments_count": 0,
            "ai_likes_count": 0,
            "author": "admin",
            "categories": [],
            "category": "Coding & Algorithms",
            "category_raw": "Coding & Algorithms",
            "comments": [],
            "comments_count": 0,
            "company": "Google",
            "content": "【Google Coding Round 2】题型类似 LC 琪琪吧，follow-up 类似 LC 气死三（大概思路）\n第二轮整体也是偏图论/最短路那种风格，题目我体感和 LC 很像（面试官也会在过程中加条件做 follow-up）。\n1）主问题（类似 778 Swim in Rising Water）\n给一个 grid / 状态图，从起点到终点，路径代价不是普通的路径和，而是“路径上遇到的最大值/最差值”（类似水位上升，只有水位 >= 该格子高度才能走）。\n我的做法是直接用 Dijkstra 的变体：\ndist[x] 表示到这个点的“最小可能最大值”（minimize the maximum along path）\n扩展邻居时用\nnew = max(dist[cur], height[nxt])\n复制代码\n用小根堆一路跑到终点就结束\n复杂度大概 O(n^2 log n)（取决于 grid 大小），实现也比较直接，面试官接受度很高。\n（我也提了一嘴：也可以 binary search 水位 + BFS/DFS 判通，但 Dijkstra 一把梭更干净。）\n2）Follow-up（类似 743 Network Delay Time）\n场景变成一般图：给边权（有向/无向看题面），问从某个 source 出发，最短时间把信号传到所有点，输出最大最短路（或者如果有点不可达返回 -1）。\n这题就是标准 Dijkstra：\n建 adjacency list\ndist 初始化 INF，source=0\n堆里弹最小 dist，松弛边\n最后看 dist 里有没有 INF，有就 -1，否则返回 max(dist)\n面试风格：\n面试官会追问你为什么这个 cost 不是普通加和、为什么 Dijkstra 还能用（关键是“满足最优子结构 + 每次确定最小 dist 的点不会被更小更新”）。\n还会问一些 corner case：比如起点=终点、不可达节点、重复入堆怎么处理（用 visited 或者\nif curDist!=dist[u] continue\n复制代码\n）。\n大概就是这些，供参考。",
            "content_enhanced": "## Problem (two related shortest-path tasks)\n\n### Part 1 — Minimize the maximum value along a grid path (\"minimax\" path)\nYou are given an `m x n` integer grid `H`, where `H[r][c]` is the “difficulty/height” of cell `(r,c)`.\n\n- Start at `(0,0)` and want to reach `(m-1, n-1)`.\n- You may move **up/down/left/right** to adjacent cells (no diagonals).\n- The **cost of a path** is **not the sum** of values; instead it is:\n\n> the maximum `H[r][c]` value encountered on that path (including start and end).\n\n**Return** the minimum possible path cost (i.e., minimize the maximum cell value you ever step on).\n\n**Assumptions/constraints (typical interview constraints):**\n- `1 <= m,n <= 200`\n- `0 <= H[r][c] <= 10^9`\n\n\n### Part 2 (follow-up) — Time for a signal to reach all nodes in a weighted graph\nYou are given a weighted graph with `n` nodes labeled `1..n` and a list of directed edges `edges`, where each edge is `(u, v, w)` meaning it takes time `w > 0` to travel from `u` to `v`.\n\nA signal starts at node `k` at time `0` and travels along edges.\n\n- Let `dist[i]` be the shortest time for the signal to reach node `i`.\n- **Return**:\n  - `max(dist[i])` over all nodes `i` if every node is reachable, or\n  - `-1` if some node is unreachable.\n\n**Assumptions/constraints (typical interview constraints):**\n- `1 <= n <= 10^5` (or smaller in an interview)\n- `1 <= |edges| <= 2*10^5`\n- `1 <= w <= 10^9`\n\n## Edge cases to consider\n- Start equals end (Part 1: `m=n=1`; Part 2: `n=1`).\n- Unreachable nodes (Part 2).\n- Multiple edges between the same nodes (Part 2).\n- Repeated states pushed into a heap/priority queue (both parts).",
            "content_raw": null,
            "created_at": "2026-01-22T00:00:00",
            "difficulty": "hard",
            "has_coding_schema": false,
            "has_schema_data": false,
            "id": 6094,
            "interview_round": "Technical Screen",
            "is_liked": false,
            "is_locked": true,
            "is_saved": false,
            "is_shared": false,
            "likes": [],
            "likes_count": 0,
            "position": "Software Engineer",
            "real_comments_count": 0,
            "real_likes_count": 0,
            "saves_count": 0,
            "schema_data": null,
            "shares_count": 0,
            "slug": "compute-minimax-grid-path-and-network-delay",
            "tags": [],
            "title": "Compute minimax grid path and network delay",
            "total_likes": 0,
            "updated_at": "2026-01-22T17:35:45.874086",
            "user_id": 1,
            "views_count": 0
        },
        {
            "ai_comments_count": 0,
            "ai_likes_count": 0,
            "author": "admin",
            "categories": [],
            "category": "Coding & Algorithms",
            "category_raw": "Coding & Algorithms",
            "comments": [],
            "comments_count": 0,
            "company": "Google",
            "content": "本帖最后由 匿名 于 2026-1-19 19:24 编辑\n题目基本和 LeetCode 把三四 一模一样：给一棵树，求每个点到所有点的距离和。\n我当时的答题节奏是“先给 baseline，再推到最优”。\n1）Baseline（非最优）\n先说：每个点都 BFS/DFS 一遍，算到所有点的距离和。\n复杂度 O(n^2)，能保证正确，但 n 大会超时。\n然后引出：树这种结构应该能用 DP / reroot 优化到 O(n)。\n2）最优解（reroot DP，两次 DFS）\n核心是先任选 0 做根，先算：\nsub[u] = u 子树大小\ndp[u] = u 子树内到 u 的距离和\n后序 DFS 递推：dp[u] += dp[v] + sub[v]（因为子树 v 里所有点到 u 都比到 v 多 1）\n算完后 ans[0] = dp[0]。\n再做一次前序 DFS 做换根（reroot），关键公式：\n从 u 换根到孩子 v：\nv 子树里的 sub[v] 个点距离 -1，其余 n-sub[v] 个点距离 +1\n所以：\nans[v] = ans[u] - sub[v] + (n - sub[v])\n= ans[u] + n - 2*sub[v]\n最终 O(n) 过。\n整体面试官挺认可这种“先朴素解保证正确，再推公式到最优”的过程。",
            "content_enhanced": "## Problem\nYou are given an undirected tree with **n** nodes labeled `0..n-1` and a list of `n-1` edges. The tree is connected and contains no cycles.\n\nFor each node `i`, compute:\n\n\\[\nans[i] = \\sum_{j=0}^{n-1} dist(i, j)\n\\]\n\nwhere `dist(i, j)` is the number of edges on the unique path between nodes `i` and `j`.\n\n## Input\n- Integer `n`\n- List `edges`, where each element is a pair `[u, v]` indicating an undirected edge between `u` and `v`\n\n## Output\n- An integer array `ans` of length `n`, where `ans[i]` is the sum of distances from node `i` to all nodes.\n\n## Constraints\n- `1 ≤ n ≤ 2 * 10^5`\n- `edges.length = n - 1`\n- `0 ≤ u, v < n`\n- The input graph is a tree.\n\n## Example\nInput:\n- `n = 4`\n- `edges = [[0,1],[1,2],[1,3]]`\n\nOutput:\n- `ans = [5,3,5,5]`\n\nExplanation:\n- From node `1`: distances to `[0,2,3]` are `[1,1,1]`, sum is `3`.\n- From node `0`: distances to `[1,2,3]` are `[1,2,2]`, sum is `5`.\n",
            "content_raw": null,
            "created_at": "2026-01-22T00:00:00",
            "difficulty": "hard",
            "has_coding_schema": false,
            "has_schema_data": false,
            "id": 6095,
            "interview_round": "Technical Screen",
            "is_liked": false,
            "is_locked": true,
            "is_saved": false,
            "is_shared": false,
            "likes": [],
            "likes_count": 0,
            "position": "Software Engineer",
            "real_comments_count": 0,
            "real_likes_count": 0,
            "saves_count": 0,
            "schema_data": null,
            "shares_count": 0,
            "slug": "compute-distance-sum-from-every-tree-node",
            "tags": [],
            "title": "Compute distance-sum from every tree node",
            "total_likes": 0,
            "updated_at": "2026-01-22T17:35:54.281816",
            "user_id": 1,
            "views_count": 0
        },
        {
            "ai_comments_count": 0,
            "ai_likes_count": 0,
            "author": "admin",
            "categories": [],
            "category": "Coding & Algorithms",
            "category_raw": "Coding & Algorithms",
            "comments": [],
            "comments_count": 0,
            "company": "HubSpot",
            "content": "OA\n往\n公司里加新职员\n那道题\n以下内容需要积分高于 150 您已经可以浏览\n注意规则限制，一个公司最多只有五个一样的岗位，还有一个员工最多只能在一家公司担任两个岗位，违反规则的话就要判断invalid并给出理由\nVO\ncoding: lc而其\nSD：design netflix/youtube",
            "content_enhanced": "## Problem\nYou are building a simple HR assignment validator for a platform with **companies**, **employees**, and **job roles**.\n\nWhen the system receives a request to assign an employee to a role in a company, it must enforce the following rules:\n\n1. **Role capacity per company:** In a given company, **each role** can be held by **at most 5 employees** at the same time.\n2. **Max roles per employee per company:** An employee can hold **at most 2 roles in the same company** at the same time.\n\nIf a request violates any rule, the system must return `invalid` and also provide a **reason**. Otherwise, it should apply the assignment and return `valid`.\n\n## Input\n- An initial set of existing assignments.\n- A sequence of `add` requests, each of the form:\n  - `employee_id`, `company_id`, `role_name`\n\n## Output\nFor each `add` request, output either:\n- `valid` (and the assignment is applied), or\n- `invalid: <reason>` where `<reason>` clearly states which rule was violated.\n\n## Notes / Clarifications\n- If an employee is already assigned to the same role in the same company, treat it as `valid` (no-op), unless you choose to define it as an error—state your assumption.\n- If both rules would be violated, you may return either a single reason or multiple reasons, but be consistent.\n\n## Constraints (you may assume)\n- Up to `10^5` total assignments and requests.\n- IDs/role names are strings.\n\n## Example (illustrative)\nGiven existing assignments where role `SWE` at company `C1` already has 5 employees, adding another `SWE` to `C1` should return:\n- `invalid: role capacity exceeded (max 5 per role per company)`\n",
            "content_raw": null,
            "created_at": "2026-01-22T00:00:00",
            "difficulty": "medium",
            "has_coding_schema": false,
            "has_schema_data": false,
            "id": 6100,
            "interview_round": "Technical Screen",
            "is_liked": false,
            "is_locked": true,
            "is_saved": false,
            "is_shared": false,
            "likes": [],
            "likes_count": 0,
            "position": "Software Engineer",
            "real_comments_count": 0,
            "real_likes_count": 0,
            "saves_count": 0,
            "schema_data": null,
            "shares_count": 0,
            "slug": "validate-hiring-request-under-role-constraints",
            "tags": [],
            "title": "Validate hiring request under role constraints",
            "total_likes": 0,
            "updated_at": "2026-01-22T17:39:06.742782",
            "user_id": 1,
            "views_count": 0
        },
        {
            "ai_comments_count": 0,
            "ai_likes_count": 0,
            "author": "admin",
            "categories": [],
            "category": "Coding & Algorithms",
            "category_raw": "Coding & Algorithms",
            "comments": [],
            "comments_count": 0,
            "company": "Snowflake",
            "content": "Tiktok OA 基本没有看到最近分享出来的原题。Tiktok OA 目前已经从 HackerRank 迁移到了Codesignal 上，考察形式从之前5选择+2编程，变成了4编程，从Codesignal题库随机抽取4道题目，所以可能不会像之前在一个周期内是完全一样的题目，最近做了\n需要tiktok的OA\n，分享下最近最新的4题\n第一题：查行列数取较小值当m，套现成公式直接算结果，每个查询秒出答案\n第二题：先看O和I数量能不能凑回文（偶长需都偶、奇长仅一个奇），不行返-1，行的话双指针往中间凑，不一样就找最近的换，记次数就行\n第三题：n*m网格走到右下角，往右移到末尾转下一行开头，碰障碍返-1、循环返-2，用map记传送位、set记访问过的格子，每次移一步、传送算一步，判好格子状态\n第四题：数组求满足上限k的最长子数组，用双指针滑动，移动左端点时调整右端点到最大满足位置（pref[r]-2*pref[l]≤k），遍历记答案，复杂度O(n)",
            "content_enhanced": "You are given four independent coding questions.\n\n## 1) Count square subgrids (multiple queries)\nFor each query, you are given two integers `R` and `C` representing an `R × C` grid of unit cells.\n\nReturn the total number of **axis-aligned square subgrids** (of all possible side lengths) that can be formed inside the grid.\n\n- **Input:** `q` queries, each query contains `R, C`.\n- **Output:** For each query, output the number of square subgrids.\n- **Constraints (typical):** `1 ≤ q ≤ 2e5`, `1 ≤ R, C ≤ 1e9`.\n\n---\n\n## 2) Minimum adjacent swaps to make a palindrome\nYou are given a string `s` of length `n` (in the OA it may be a binary string such as only `'O'` and `'I'`, but assume it can be any characters).\n\nIn one move, you may swap two **adjacent** characters.\n\nReturn the **minimum number of adjacent swaps** needed to rearrange `s` into a palindrome.\n\n- If it is impossible to form a palindrome, return `-1`.\n\n---\n\n## 3) Row-major grid walk with obstacles, teleports, and loop detection\nYou are given an `n × m` grid. You start at the top-left cell `(0,0)` and want to reach the bottom-right cell `(n-1,m-1)`.\n\nMovement rule (row-major walk):\n- From `(r,c)`, your next step is normally:\n  - `(r, c+1)` if `c+1 < m`\n  - otherwise wrap to the start of the next row `(r+1, 0)` if `r+1 < n`\n\nAdditional rules:\n- Some cells are **blocked** (obstacles). If you ever step onto a blocked cell, stop and return `-1`.\n- Some cells are **teleporters**. If you step onto a teleporter cell, you are immediately moved to its paired destination cell.\n  - Treat teleporting as part of the same “step”: each transition (including landing on a teleporter and being transported) counts as **one step total**.\n- If the process enters a cycle and will never reach the target, return `-2`.\n\nReturn the number of steps to reach `(n-1,m-1)` if reachable.\n\n---\n\n## 4) Longest subarray under a prefix-sum inequality\nYou are given an array `a` of length `n` (assume `a[i] ≥ 0`) and an integer `k`.\n\nLet prefix sums be:\n- `pref[0] = 0`\n- `pref[i+1] = pref[i] + a[i]`\n\nFind the maximum length of a subarray `[l, r)` (with `0 ≤ l < r ≤ n`) such that:\n\n\\[\n\\text{pref}[r] - 2\\cdot\\text{pref}[l] \\le k\n\\]\n\nReturn this maximum length.\n",
            "content_raw": null,
            "created_at": "2026-01-22T00:00:00",
            "difficulty": "hard",
            "has_coding_schema": false,
            "has_schema_data": false,
            "id": 6106,
            "interview_round": "Technical Screen",
            "is_liked": false,
            "is_locked": true,
            "is_saved": false,
            "is_shared": false,
            "likes": [],
            "likes_count": 0,
            "position": "Software Engineer",
            "real_comments_count": 0,
            "real_likes_count": 0,
            "saves_count": 0,
            "schema_data": null,
            "shares_count": 0,
            "slug": "solve-four-oa-algorithm-problems",
            "tags": [],
            "title": "Solve four OA algorithm problems",
            "total_likes": 0,
            "updated_at": "2026-01-22T17:41:44.827649",
            "user_id": 1,
            "views_count": 0
        }
    ]


'''